batch_size: 64
bi_encoder: true
layers: 2
dropout_prob: 0.2
cell_type: LSTM
cell_size: 8
time_major: true
attention: null
optimizer: GradientDescentOptimizer
save_all_gradients: false
generate_log_dir: true
test_size: derive
infer_vocab: false
